cc_library(
    name = "cpputils",
    hdrs = ["cpputils.h"],
    visibility = ["//:__subpackages__"],
)

py_library(
    name = "pyutils",
    srcs = ["pyutils.py"],
    visibility = ["//:__subpackages__"],
)
