cc_library(
    name = "cpputils",
    srcs = ["cpputils.cpp"],
    hdrs = ["cpputils.h"],
    visibility = ["//days:__subpackages__"],
)

py_library(
    name = "pyutils",
    srcs = ["pyutils.py"],
    visibility = ["//days:__subpackages__"],
)
